import { OnInit, ElementRef, Renderer, EventEmitter } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
export declare class TextAreaEditorComponent implements ControlValueAccessor, OnInit {
    private _renderer;
    textareaEditorControl: ElementRef;
    label: string;
    required: boolean;
    disabled: string;
    id: string;
    stringlength: string;
    maxheight: string;
    minheight: string;
    onSave: EventEmitter<string>;
    onCancel: EventEmitter<string>;
    private _value;
    private preValue;
    private editing;
    onChange: any;
    onTouched: any;
    constructor(element: ElementRef, _renderer: Renderer);
    onSaveComplete(): void;
    onCancelComplete(): void;
    value: any;
    writeValue(value: any): void;
    registerOnChange(fn: (_: any) => {}): void;
    registerOnTouched(fn: () => {}): void;
    onBlur($event: Event): void;
    edit(value: any): void;
    ngOnInit(): void;
}
